# Generated by Django 2.2 on 2020-08-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_plan_name', models.CharField(blank=True, max_length=30)),
                ('coin_plan_description', models.CharField(blank=True, max_length=30)),
                ('coin_plan_price', models.CharField(blank=True, max_length=30)),
                ('coin_amount', models.CharField(blank=True, max_length=30)),
                ('play_store_product_id', models.CharField(blank=True, max_length=30)),
                ('app_store_product_id', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoinRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('default_coin', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_tag_name', models.CharField(blank=True, max_length=30)),
                ('move_explore', models.BooleanField(default=True)),
                ('move_to_banner', models.BooleanField(default=False)),
                ('hash_tag_profile', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.CharField(blank=True, max_length=60)),
                ('post_hash_tage', models.CharField(blank=True, max_length=60)),
                ('post_video', models.FileField(upload_to='PostVideos/')),
                ('post_video_image', models.URLField(blank=True)),
                ('video_view_count', models.IntegerField(default=0)),
                ('video_likes_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('priority', models.IntegerField(blank=True, default=-1)),
                ('post_mod', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_request_type', models.CharField(blank=True, max_length=30)),
                ('account', models.CharField(blank=True, max_length=30)),
                ('amount', models.CharField(blank=True, max_length=30)),
                ('user_id', models.CharField(blank=True, max_length=30)),
                ('created_date', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RewardingAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(blank=True, max_length=30)),
                ('coin', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sound_category_profile', models.ImageField(blank=True, null=True, upload_to='SoundCategory/')),
                ('move_to_banner', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=30)),
                ('otp', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_mobile_no', models.CharField(blank=True, max_length=15)),
                ('is_mobile_verify', models.BooleanField(default=False)),
                ('user_profile', models.ImageField(blank=True, upload_to='Profiles/')),
                ('login_type', models.CharField(blank=True, max_length=30)),
                ('identity', models.EmailField(blank=True, max_length=254)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('device_token', models.CharField(blank=True, max_length=200)),
                ('token', models.CharField(blank=True, max_length=200)),
                ('is_verify', models.BooleanField(default=False)),
                ('total_received', models.IntegerField(default=0)),
                ('total_send', models.IntegerField(default=0)),
                ('my_wallet', models.IntegerField(default=0)),
                ('spen_in_app', models.IntegerField(default=0)),
                ('check_in', models.IntegerField(default=0)),
                ('upload_video', models.IntegerField(default=0)),
                ('from_fans', models.IntegerField(default=0)),
                ('purchased', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('fb_url', models.URLField(blank=True)),
                ('insta_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerificationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('photo_id_image', models.ImageField(blank=True, null=True, upload_to='UserVerificationsImages/')),
                ('photo_with_id_image', models.ImageField(blank=True, null=True, upload_to='UserVerificationsImages/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for_verification', to='api.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_title', models.CharField(blank=True, max_length=200, null=True)),
                ('sound', models.FileField(upload_to='Sounds/')),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('singer', models.CharField(blank=True, max_length=100, null=True)),
                ('sound_image', models.ImageField(blank=True, null=True, upload_to='SoundImages/')),
                ('added_by', models.CharField(default='user', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('sound_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_category', to='api.SoundCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('contact_info', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to='api.Users')),
            ],
        ),
        migrations.CreateModel(
            name='PostVideoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_video_image', models.ImageField(upload_to='PostVideoImage/')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='api.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='api.Sound'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_post', to='api.Users'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('received_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to='api.Users')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='api.Users')),
            ],
        ),
        migrations.CreateModel(
            name='LikesVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes_videos', to='api.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_likes_videos', to='api.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='api.Users')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='api.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_post', to='api.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_comment', to='api.Users')),
            ],
        ),
    ]
